"""add role column to user

Revision ID: 6e7acf8c8487
Revises: f72fdfc1503a
Create Date: 2025-01-21 23:36:49.692873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e7acf8c8487'
down_revision: Union[str, None] = 'f72fdfc1503a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('role', sa.Enum('ADMIN', 'USER', name='role'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'role')
    # ### end Alembic commands ###
